#!/bin/sh
set -e

echo 'Will overwrite your current configuration, continue? (Yes,no)'
read answer

case "$answer" in
	[Yy]*|"");;
	[Nn]|no) exit 0;;
esac

PREFIX="${PREFIX:-$HOME}"

cp zshrc "$PREFIX/.zshrc"
cp zshenv "$PREFIX/.zshenv"
[ -d "$PREFIX/.zsh.d" ] || mkdir "$PREFIX/.zsh.d"
cp -rv zsh.d/* "$PREFIX/.zsh.d"
