#!/bin/sh
set -e

echo 'Will overwrite your current configuration, continue? (Yes,no)'
read answer

case "$answer" in
	[Yy]*|"");;
	[Nn]|no) exit 0;;
esac

cp zshrc ~/.zshrc
cp zshenv ~/.zshenv
cp -rv zsh.d ~/.zsh.d
